### ISSUE TITLE
PHPUnit execution fails due to ""docker.exe": executable file not found in %PATH%"

### ISSUE THREAD

**Issue by shochdoerfer** [php-perfect/ddev-intellij-plugin#187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [ ] I am sure

### Describe the bug

This may or may not be similar to #152.

I have 2 DDEV projects, pretty similar setups. The minor difference is that a different database is used. In one project, the PHPUnit integration works out of the box, thanks to the defaults configured by this plugin. In the other project, I got the following error when I try to execute PHPUnit: 
```
exec: "docker.exe": executable file not found in %PATH%
Current PATH : 
```

The issue seems to be that PHPStorm can't find the PHP installation in the CLI interpreter configured by DDEV. When trying to find the interpreter PHPStorm returns an error "Failed to parse validation script output"

![php](https://github.com/php-perfect/ddev-intellij-plugin/assets/596449/19c187c9-4f15-490b-a582-69aec8b3a7c7)

The same also happens for a colleague when cloning the repo. We don't share the `.idea` directory via Git, so both installations on 2 different laptops behave exactly the same.

Interestingly I was able to manually fix this problem this morning by adding another CLI interpreter with the exact same settings as defined by the DDEV one. Once I assigned that manually added CLI interpreter to the PHPUnit configuration, it executed just fine.

I compared both .idea directories of the project with a working DDEV setup and the project where it did not work. And the only difference I could spot was a missing `<component name="PhpInterpretersPhpInfoCache">` element in the php.xml configuration. When I copied that part into the project that was not working, PHPStorm at least did not show me an error in the UI, but still, I could not execute PHPUnit.

Most likely, this seems to be a regression or a bug in PHPStorm. Not sure if this plugin can do something about it.

**Comment by shochdoerfer** [comment]
I forgot to mention: On the first try, I deleted all the DDEV resources that got created automatically. But that did not help either.

**Comment by mwaltonen** [comment]
I'm having the same issue here.  In `php.xml`, if I update

```
<envs pass-parent-envs="false">
  <env name="COMPOSE_PROJECT_NAME" value="ddev-test-project" />
</envs>
```
to
```
<envs>
  <env name="COMPOSE_PROJECT_NAME" value="ddev-test-project" />
</envs>
```
everything works as before. This appears to correspond to placing a check next to "Include system environment variables" when you expand the "Environment variables" field in the "CLI Interpreters" settings.

**Comment by ultimike** [comment]
I'm having a similar issue and while checking the "Include system environment variables" box does change the error for me, it doesn't solve the issue.

![Screenshot 2023-07-07 at 3 33 07 PM](https://github.com/php-perfect/ddev-intellij-plugin/assets/1727889/071a6e41-52f2-48b5-9b17-f6929dd3e072)

After checking the box, when I attempt to validate my phpcs settings, I get a "Could not open input file: /var/www/html/vendor/bin/phpcs" error message.

-mike

**Comment by rfay** [comment]
If you want to come over to Discord we can schedule some live debugging and see if we can sort this out.

**Comment by mwaltonen** [comment]
Did you click the little spinning wheel icon to detect your php version after checking the box?

**Comment by ultimike** [comment]
@rfay Thanks, for the offer - I might take you up on this depending on what you think about what I found (keep reading).

@mwaltonen I think you're referring to the "Reload phpinfo" button on the "PHP | CLI interpreter" settings page, correct? If so, yes, I did that (8.1.6) and after that, still the same issue with phpcs as I mentioned above.

@shochdoerfer Thanks for the suggestion - that worked. Recreating the DDEV CLI interpreter instead of relying on the one that this project provides did the trick. Obviously, this makes me think that maybe there's something that has been updated in PhpStorm that breaks that particular bit of functionality in the plugin? I'm using PhpStorm 2023.1.3

-mike

**Comment by rfay** [comment]
Congrats on the progress! I think creating new configs in PhpStorm is often the ticket.

**Comment by nico-loeber** [comment]
Hey @shochdoerfer,

My guess would be, that the php info cache got lost and was not automatically regenerated.
The PHPInfo Cache is created by the plugin on any change to the interpreter configuration and is often triggert when clicking ddev restart in the UI. You can see a progress bar for a short period of time saying something like "Checking PHP Installation" or something like that.
I was not able to reproduce this error. Maybe a PHPStorm update cleared this cache? Is the problem solved after updating the cache (The progress bar popup appeared)?

Sorry for my late reply.

**Comment by Kayu84** [comment]
came here cause i found an solution for me, doing the same "manual" fix described here: 
https://blog.bitexpert.de/blog/ddev_intellij_plugin_phpunit_error 

> Since I was running out of ideas, I decided to create a new CLI Interpreters entry myself and copy all the data from the entry created by DDEV. Once I was done, I configured PHPUnit to use the newly created CLI Interpreter. And guess what? This time it worked. I informed my colleague, and the "fix" also worked on this machine. Problem solved.

watching this issue and hope for a fix in futer.

**Comment by Kayu84** [comment]
@rfay: I know about the youtrack, just wanted to share my workaround (Stephan's) workaround.
No, php-cs-fixer is not the solution. But I wanted to use php-cs-fixer with DDEV Integration. (In Case of cli Interpreter, PHP Version from docker-compose: https://www.jetbrains.com/help/phpstorm/using-php-cs-fixer.html#installing-configuring-php-cs-fixer)

**Comment by rfay** [comment]
Right, if you could give a complete answer for a novice user, explaining all the things, it would be awesome. Remember not all of us are as engaged with either PhpStorm or PHP or testing as you are, thanks!

**Comment by nico-loeber** [comment]
I would be very interested in a way to reproduce this error. Otherwise I'm very limited in my actions...

**Comment by shochdoerfer** [comment]
@nico-loeber contact me, I think we can make something happen.

**Comment by nico-loeber** [comment]
Thanks to @shochdoerfer I was able to reproduce this behavior.
The only difference between the manually created php interpreter configuration and the one created by the plugin was, that the environment variables of the parent process were not included for the plugins one.
I changed this behavior and this seems to fix this bug.

Fixed in https://github.com/php-perfect/ddev-intellij-plugin/pull/214.

The fix will most probably be released with the next version of the plugin that is required for compatibility to PHPStorm 2023.2.

**Comment by nico-loeber** [comment]
Fix is merged and released in [1.1.1](https://github.com/php-perfect/ddev-intellij-plugin/releases/tag/1.1.1).

**Comment by alexbogias** [comment]
Looks like is better now when added docker binary path to environmental variables but i still get:
![image](https://github.com/php-perfect/ddev-intellij-plugin/assets/1313467/e7eb523d-c455-47fe-b9c3-94fee152f24c)

@nico-loeber You can have a quick look if you want with screen share...

**Comment by nico-loeber** [comment]
Are you sure you are using the latest release of the plugin? It is still pending review by JetBrains and requires PHPStorm 2023.2 which will probably be released within the next few days.

Of course you can test it by downloading the the plugin from the release artifacts and use it in a PHPStorm Release Candidate / EAP Version.

**Comment by rfay** [comment]
(Thanks for the great work on this and so many other things @nico-loeber !)
